// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Bus struct {
	ID             int64     `json:"id"`
	BusNumber      string    `json:"bus_number"`
	BusPlateNumber string    `json:"bus_plate_number"`
	Capacity       int32     `json:"capacity"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Driver struct {
	ID           int64     `json:"id"`
	FullName     string    `json:"full_name"`
	KimlikNumber string    `json:"kimlik_number"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Password     string    `json:"password"`
}

type Passenger struct {
	ID           int64     `json:"id"`
	FullName     string    `json:"full_name"`
	KimlikNumber string    `json:"kimlik_number"`
	Password     string    `json:"password"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Payment struct {
	ID          int64     `json:"id"`
	AmountPaid  float64   `json:"amount_paid"`
	PaymentDate time.Time `json:"payment_date"`
	PassengerID int64     `json:"passenger_id"`
	CreatedAt   time.Time `json:"created_at"`
}

type Schedule struct {
	ID                   int64     `json:"id"`
	BusID                int64     `json:"bus_id"`
	DriverID             int64     `json:"driver_id"`
	StartingPoint        string    `json:"starting_point"`
	Destination          string    `json:"destination"`
	ScheduleDate         time.Time `json:"schedule_date"`
	DepartureTime        time.Time `json:"departure_time"`
	EstimatedArrivalTime time.Time `json:"estimated_arrival_time"`
	FareAmount           float64   `json:"fare_amount"`
	Remarks              string    `json:"remarks"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type SchedulePassenger struct {
	PassengerID int64     `json:"passenger_id"`
	ScheduleID  int64     `json:"schedule_id"`
	CreatedAt   time.Time `json:"created_at"`
}
