// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: passenger.sql

package db

import (
	"context"
)

const createPassenger = `-- name: CreatePassenger :one
INSERT INTO passenger (full_name, kimlik_number, password)
VALUES ($1, $2, $3)
RETURNING id, full_name, kimlik_number, password, created_at, updated_at
`

type CreatePassengerParams struct {
	FullName     string `json:"full_name"`
	KimlikNumber string `json:"kimlik_number"`
	Password     string `json:"password"`
}

func (q *Queries) CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, createPassenger, arg.FullName, arg.KimlikNumber, arg.Password)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.KimlikNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePassenger = `-- name: DeletePassenger :one
DELETE FROM passenger
WHERE id = $1
RETURNING id, full_name, kimlik_number, password, created_at, updated_at
`

func (q *Queries) DeletePassenger(ctx context.Context, id int64) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, deletePassenger, id)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.KimlikNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPassenger = `-- name: GetPassenger :one
SELECT id, full_name, kimlik_number, password, created_at, updated_at
FROM passenger
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPassenger(ctx context.Context, id int64) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, getPassenger, id)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.KimlikNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPassengers = `-- name: ListPassengers :many
SELECT id, full_name, kimlik_number, password, created_at, updated_at
FROM passenger
LIMIT $1
OFFSET $2
`

type ListPassengersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPassengers(ctx context.Context, arg ListPassengersParams) ([]Passenger, error) {
	rows, err := q.db.QueryContext(ctx, listPassengers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Passenger{}
	for rows.Next() {
		var i Passenger
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.KimlikNumber,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassenger = `-- name: UpdatePassenger :one
UPDATE passenger
SET full_name = $1
RETURNING id, full_name, kimlik_number, password, created_at, updated_at
`

func (q *Queries) UpdatePassenger(ctx context.Context, fullName string) (Passenger, error) {
	row := q.db.QueryRowContext(ctx, updatePassenger, fullName)
	var i Passenger
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.KimlikNumber,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
