// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateBus(ctx context.Context, arg CreateBusParams) (Bus, error)
	CreateDriver(ctx context.Context, arg CreateDriverParams) (Driver, error)
	CreatePassenger(ctx context.Context, arg CreatePassengerParams) (Passenger, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error)
	CreateSchedulePassenger(ctx context.Context, arg CreateSchedulePassengerParams) (SchedulePassenger, error)
	DeleteBus(ctx context.Context, id int64) (Bus, error)
	DeleteDriver(ctx context.Context, id int64) (Driver, error)
	DeletePassenger(ctx context.Context, id int64) (Passenger, error)
	DeleteSchedule(ctx context.Context, id int64) (Schedule, error)
	DeleteSchedulePassenger(ctx context.Context, arg DeleteSchedulePassengerParams) (SchedulePassenger, error)
	GetBus(ctx context.Context, id int64) (Bus, error)
	GetDriver(ctx context.Context, id int64) (Driver, error)
	GetPassenger(ctx context.Context, id int64) (Passenger, error)
	GetPassengerPayments(ctx context.Context, passengerID int64) ([]Payment, error)
	GetPassengerSchedules(ctx context.Context, passengerID int64) ([]SchedulePassenger, error)
	GetSchedule(ctx context.Context, id int64) (Schedule, error)
	ListBuses(ctx context.Context) ([]Bus, error)
	ListDrivers(ctx context.Context, arg ListDriversParams) ([]Driver, error)
	ListPassengers(ctx context.Context, arg ListPassengersParams) ([]Passenger, error)
	ListSchedules(ctx context.Context) ([]Schedule, error)
	UpdateBus(ctx context.Context, capacity int32) (Bus, error)
	UpdateDriver(ctx context.Context, fullName string) (Driver, error)
	UpdatePassenger(ctx context.Context, fullName string) (Passenger, error)
	UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error)
}

var _ Querier = (*Queries)(nil)
